/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface SkyButton {
      'className': string;
      'content': string;
      'modifier': string;
      'stateModifier': string;
    }
  }

  interface HTMLSkyButtonElement extends StencilComponents.SkyButton, HTMLStencilElement {}

  var HTMLSkyButtonElement: {
    prototype: HTMLSkyButtonElement;
    new (): HTMLSkyButtonElement;
  };
  interface HTMLElementTagNameMap {
    'sky-button': HTMLSkyButtonElement;
  }
  interface ElementTagNameMap {
    'sky-button': HTMLSkyButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'sky-button': JSXElements.SkyButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SkyButtonAttributes extends HTMLAttributes {
      'className'?: string;
      'content'?: string;
      'modifier'?: string;
      'stateModifier'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
